# Generated by Django 5.1.1 on 2024-09-25 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="errorlog",
            old_name="error_description",
            new_name="description",
        ),
        migrations.AddField(
            model_name="errorlog",
            name="error_type",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="errorlog",
            name="resolution_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="errorlog",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="error_logs",
                to="logs.staff",
            ),
        ),
    ]
