# Generated by Django 5.1.1 on 2024-09-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_rename_error_description_errorlog_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="errorlog",
            name="resolution_status",
        ),
    ]
